<link rel="shortcut icon" href="/assets/images/logo.ico?sio-use-cdn=enabled">
<link type="text/less" rel="stylesheet" href="/assets/less/homepage.less?sio-css-embed=enabled">

<script type="text/javascript" src="/assets/js/less-local-development-support.js?sio-local-development-only=enabled"></script>
<script type="text/javascript" src="/assets/vendor/less-1.7.3/less-1.7.3.js?sio-local-development-only=enabled"></script>

